# Terraform Tasks

tasks:
  lint:terraform:format:
    context: powershell
    description: Perform Terraform Format Check
    command:
      - |
        tenv tf list
        terraform version

        Invoke-Terraform -Format -Path $env:TF_FILE_LOCATION -Debug

  lint:terraform:validate:
    context: powershell
    description: Perform Terraform Validation
    command:
      - |
        tenv tf list
        terraform version

        Invoke-Terraform -Validate -Path $env:TF_FILE_LOCATION

  lint:terraform:tflint:
    context: powershell
    description: Perform Terraform Linting using TFLint
    command:
      - |
        tflint --version
        Write-Host ("Path: {0}" -f $env:TF_FILE_LOCATION)

        tflint --init
        tflint --chdir=$env:TF_FILE_LOCATION

  terraform:init:
    context: powershell
    description: Initialise Terraform
    command: |
      Invoke-Terraform -Init -Arguments $env:TF_BACKEND_INIT -Path $env:TF_FILE_LOCATION -Debug

      Invoke-Terraform -Workspace -Arguments $env:ENV_NAME -Path $env:TF_FILE_LOCATION -Debug

  terraform:plan:
    context: powershell
    description: Terraform Plan
    command:
      - |
        $arguments = @("-input=false", "-out=`"deploy.tfplan`"")
        if ($env:WORKSPACE_VARS_FILE) {
          $arguments += "--var-file=$env:WORKSPACE_VARS_FILE"
        }
        Invoke-Terraform -Plan -Path $env:TF_FILE_LOCATION -Arguments $arguments

  terraform:apply:
    context: powershell
    description: Apply Terraform Plan
    command: |
      Push-Location $env:TF_FILE_LOCATION

      Invoke-Terraform -Apply -Path deploy.tfplan -Debug

      terraform output -json | Set-Content -Path ./tfoutputs.json -Force

  terraform:destroy:plan:
    context: powershell
    description: Terraform Destroy Plan
    command:
      - |
        $arguments = @("-destroy", "-input=false", "-out=`"destroy.tfplan`"")
        if ($env:WORKSPACE_VARS_FILE) {
          $arguments += "--var-file=$env:WORKSPACE_VARS_FILE"
        }
        Invoke-Terraform -Plan -Path $env:TF_FILE_LOCATION -Arguments $arguments -debug

  terraform:destroy:apply:
    context: powershell
    description: Terraform Destroy Apply
    command:
      - Push-Location $env:TF_FILE_LOCATION && Invoke-Terraform -Apply -Path destroy.tfplan -Debug

  doc:terraform:generate:
    context: powershell
    description: Generate Terraform Module Documentation
    command:
      - |
        terraform-docs --version
        terraform-docs $env:TF_FILE_LOCATION

        git config --global --add safe.directory "/app"
        git diff --exit-code . ":(exclude)$env:TF_FILE_LOCATION/.terraform.lock.hcl"
